apiVersion: v1
kind: Pod
metadata:
  name: sample
  labels:
    app: echo
spec:                               # spec - z jakich kontenerów ma się składać
  containers:
    - name: echo
      image: mendhak/http-https-echo
      ports:
        - containerPort: 8080       # port na jakim nasłuchuje kontener wewnątrz
          name: echo-port
